version: '3'

tasks:
    tsc:
        method: timestamp
        sources:
            - src/**/*.ts
        generates:
            - dist/**/*.js
        cmds:
            - npx tsc -d

    testx:
        method: none
        deps: [tsc]
        sources:
            - test/**/*.tap.*js*
        cmds:
            - npx tap {{.CLI_ARGS}}

    c8tap:
        method: none
        deps: [tsc]
        sources:
            - test/**/*.tap.*js*
        cmds:
            - |
                npx c8 tap {{.CLI_ARGS}}
                npm run c8rephtml
