name: CI

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WPT_ROOT: .wpt
      WPT_URL: https://github.com/web-platform-tests/wpt/archive/refs/tags/merge_pr_30022.tar.gz
      # WPT_HASH: 1

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

      - run: npm i
      - run: npm i -g --no-save codecov c8 typescript eslint prettier
      - run: |
          wget https://github.com/biojet1/saxes/archive/refs/heads/master.tar.gz
          tar xvzf master.tar.gz
          cd saxes-master
          npm i typescript
          npm run build

      - run: npm i saxes-master/build/dist
      - run: npm run build --if-present
      - run: npm run compile

      - name: Cache WPT
        uses: actions/cache@v2
        env:
          cache-name: wpt
        with:
          path: ${{ env.WPT_ROOT }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.WPT_URL }}-${{ hashFiles('test/wpt-patch.sh') }}
      - run: |
          echo [$HOME]
          ls
          [ -d "$WPT_ROOT" ] || mkdir -vp "$WPT_ROOT"
          if [ ! -f "$WPT_ROOT/README.md" ]; then
            curl -L "$WPT_URL" | tar xvzf - -C "$WPT_ROOT" --strip-components 1
            . test/wpt-patch.sh
          fi

      - run: npm run c8test
      - run: |
          mkdir -p coverage
          npm run c8report
          # cat coverage/lcov.info

      - name: tsc strict
        run: |
          tsc -d --sourceMap --strict --noUnusedLocals --noUnusedParameters --noImplicitOverride || true


      - name: Pack
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir .pkg
          npm pack .

      - uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: release
          path: release

      - name: Push Release
        if: github.ref == 'refs/heads/main'
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          cd release
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@github.com"
          git rm -rf .
          tar -xzf ../*-*.*.tgz --strip=1 package
          bash ../.github/workflows/sanitize.sh || true
          git add -A
          if [[ -z $(git status -s) ]]
          then
            echo "No changes"
          else
            git commit -m 'R '"$COMMIT_MESSAGE"
            git push
          fi

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          # path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
