name: Test

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm i

      - run: npm i codecov c8 --save-dev

      - run: npm run build --if-present

      - run: npm run compile

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

      # - run: npm run "test+cov"
      # - run: npm run "posttest"
      - run: npm run c8test
      - run: |
          npm run c8report
          mkdir -p coverage
          cat coverage/lcov.info

      - run: find . -name '*lcov*'

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
#           path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
