name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm i

      - run: npm i codecov --save-dev

      - run: npm run build --if-present

      - run: npm run compile

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

      - run: npm run "test+cov"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}