name: Test

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WPT_ROOT: .wpt
      WPT_URL: https://github.com/web-platform-tests/wpt/archive/refs/tags/merge_pr_30022.tar.gz

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

      - run: npm i

      - run: npm i codecov c8 typescript@rc --save-dev

      - run: cat package-lock.json

      - run: npm run build --if-present

      - run: npm run compile

      - name: Cache WPT
        uses: actions/cache@v2
        env:
          cache-name: wpt
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ${{ env.WPT_ROOT }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.WPT_URL }}

      - run: |
          echo [$HOME]
          ls
          [ -d "$WPT_ROOT" ] || mkdir -vp "$WPT_ROOT"
          cd "$WPT_ROOT"
          [ -f README.md ] || ( curl -L "$WPT_URL" | tar xvzf - --strip-components 1 )

      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist
      #     path: |
      #       dist

      - run: npm run c8test
      - run: |
          mkdir -p coverage
          npm run c8report
          cat coverage/lcov.info

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          # path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
