name: UML

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

      - run: npm i "git://github.com/biojet1/svggeom#main"
      - run: npm i
      - run: npm i tplant typescript --save-dev

      # - run: cat package-lock.json

      - run: npx tplant --input src/**/*.ts --output uml.svg

      - name: upload_uml
        uses: actions/upload-artifact@v2
        with:
          path: uml.svg
