name: UML

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

      - run: npm i tplant typescript tsuml2
      - run: npm i

      # - run: cat package-lock.json

      # - run: npx tplant --input 'src/**/*.ts' -p tsconfig.json -A --output uml.svg
      - run: npx tsuml2 --glob "./src/**/*.ts"  -o uml.svg

      - name: upload_uml
        uses: actions/upload-artifact@v2
        with:
          path: uml.svg
